# -*- coding: utf-8 -*-
"""numpypractice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HypGcTtMJBMOUQyFCbQQG_YsL_gnfLn4
"""

import numpy as np
arr=np.arange(5,51,5)
arr

arr = np.ones((4, 3))
print(arr)

arr = np.linspace(0, 1, 6)
print(arr)

identity = np.eye(3)
print(identity)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)

lst = [10, 20, 30, 40, 50]
arr = np.array(lst)

print(arr)

arr = np.arange(16)
matrix = arr.reshape(4, 4)

print(matrix)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat_flatten = arr.flatten()
flat_ravel = arr.ravel()

print("Original array", arr)
print("Using flatten():", flat_flatten)
print("Using ravel():  ", flat_ravel)

arr = np.array([10, 20, 30, 40, 50])

middle = arr[len(arr) // 2]
print(middle)

arr = np.array([10, 20, 30, 40, 50])

reversed_arr = arr[::-1]

print(reversed_arr)

arr = np.array([10, 20, 30, 40, 50, 60])

even_indexed = arr[::2]

print(even_indexed)

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

last_column = arr[:, -1]

print(last_column)

arr = np.array([10, 20, 30, 40, 50, 60])

alternate_elements = arr[1::2]

print(alternate_elements)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_matrix = matrix[:2, :2]

print(sub_matrix)

arr = np.array([10, 20, 30, 40, 50])

middle_elements = arr[1:-1]

print(middle_elements)

arr = np.array([10, 20, 30, 40, 50])

greater_than_25 = arr[arr > 25]

print(greater_than_25)

arr = np.array([10, -5, 20, -15, 30])

arr[arr < 0] = 0

print(arr)

arr = np.array([3, 5, 9, 10, 12, 14, 15])

divisible_by_3 = arr[arr % 3 == 0]

print(divisible_by_3)

arr = np.array([10, 20, 30, 40, 50])

mean_value = arr.mean()
count = np.sum(arr > mean_value)

print("Mean:", mean_value)
print("Number of elements greater than mean:", count)

arr = np.array([10, 50, 30, 50, 20])

indices = np.where(arr == 50)

print(indices)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


result = arr1 + arr2
print(result)

arr = np.array([1, 2, 3, 4, 5])


result = arr + 10

print(result)

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = A + B
print(C)